###
GET http://localhost:3000/crypto/10/1
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6bnVsbCwiaWF0IjoxNzQ3MDk3NDg5LCJleHAiOjE3NDcxODM4ODl9.6WW7-ztiXORr20m2LHcgA6gQNaj5pHoo72zrH_4YXKo"