###
GET http://localhost:3000/user
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6bnVsbCwiaWF0IjoxNzQ3MTA5MjI0LCJleHAiOjE3NDcxOTU2MjR9.omqIXkmXe2M2Ur32i63jA6UHh21jvvwwygEDzqzLOd4"

###
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "teste",
  "email": "brunoluiz234@gmail.com",
  "password": "123123"
}

###
GET http://localhost:3000/user/682295bf600bbb29398971dc
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6bnVsbCwiaWF0IjoxNzQ3MTA5MjI0LCJleHAiOjE3NDcxOTU2MjR9.omqIXkmXe2M2Ur32i63jA6UHh21jvvwwygEDzqzLOd4"

###
PATCH http://localhost:3000/user/682295bf600bbb29398971dc
Content-Type: application/json
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6bnVsbCwiaWF0IjoxNzQ3MTA5MjI0LCJleHAiOjE3NDcxOTU2MjR9.omqIXkmXe2M2Ur32i63jA6UHh21jvvwwygEDzqzLOd4"

{
  "id": "682295bf600bbb29398971dc",
  "name": "Bruno Luiz dos Santos",
  "description": "Descrição de teste.",
  "image": "123123213.png"
}

###
DELETE http://localhost:3000/user/682295bf600bbb29398971dc
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6bnVsbCwiaWF0IjoxNzQ3MTA5MjI0LCJleHAiOjE3NDcxOTU2MjR9.omqIXkmXe2M2Ur32i63jA6UHh21jvvwwygEDzqzLOd4"