###
GET http://localhost:3000/crypto/10/1
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6bnVsbCwiaWF0IjoxNzQ3MTA5MjI0LCJleHAiOjE3NDcxOTU2MjR9.omqIXkmXe2M2Ur32i63jA6UHh21jvvwwygEDzqzLOd4"