/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    AppNavigation: typeof import('./components/AppNavigation.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    ImageLogo: typeof import('./components/ImageLogo.vue')['default']
    LoginPage: typeof import('./components/LoginPage.vue')['default']
    ProfilePage: typeof import('./components/ProfilePage.vue')['default']
    RegisterPage: typeof import('./components/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
